### PR TITLE
Power Requirements

### PR DESCRIPTION
**Pull request by robfairh**
This PR addresses #17 and #18.
This PR contains the following files:

* lte-energy-req.ipynb: jupyter notebook that contains the analysis of the energy requirements of conventional electrolysis.

* hte-energy-req.ipynb: jupyter notebook that contains the analysis of the energy requirements of high-temperature electrolysis.

* sulfur-iodine.ipynb: jupyter notebook that contains the analysis of the energy requirements of the sulfur-iodine thermochemical cycle.

* hydrogen.py: contains all the important functions necessary to calculate the energy requirements and production rate of the 3 hydrogen production methods.

* figures: folder that contains a lot of new figures, it also contains .tex files to produce some of the diagrams in the jupyter notebooks

[update]: Added addressed issues and a description of a new file.

### CODE REVIEW

**Comment by samgdotson** [comment]
A little bit odd that you have your LaTeX files in the ``figures`` folder. Also, ``make`` doesn't produce a pdf file... 
Okay I think I see what happened, you're using tikz to produce png files for your presentation, right?

**Comment by robfairh** [comment]
Correct

**Comment by samgdotson** [comment]
I cannot recreate the images from the files you have. I've tried ``make`` and ``make -B``. Is there anything else you're supposed to do? Which files are required for making the images?

**Comment by samgdotson** [comment]
You mention multiple ``.ipynb`` files in the pull request but I only see one... I also tried ``find ./ -name "*.ipynb"`` and it turned up only ``sulfur-iodine.ipynb``. Did you forget to commit the other jupyter notebooks?

**Comment by robfairh** [comment]
To make the figures you need to do “make” and that will give you an instruction. I think it is “make -f hte2.makefile”. If you want to build other images you will need to change the name of the .tex you want to build in the makefile.

**Comment by robfairh** [comment]
And you are right, my last commit changes the names of the ipynb files, and I forgot to add those. My bad. I will fix it in my next commit.

**Review by samgdotson — APPROVED** [review]
Everything looks good, I'm looking forward to your presentation! 

``make -f hte2.makefile`` builds a pdf and png of one figure (because everything else is commented out).  

I had a few subjective comments:
1) When you have links to sources in the markdown cells, I'd recommend making a hyperlink rather than leaving the full URL in the text. 
E.g. Here's a link to a [humorous meme](https://www.reddit.com/r/ProgrammerHumor/comments/gt7vnm/my_teacher_said_he_was_impressed_by_my_github/) 
rather than https://www.reddit.com/r/ProgrammerHumor/comments/gt7vnm/my_teacher_said_he_was_impressed_by_my_github/. 
2. Sometimes it's unclear where you get some of your figures from (I know the link is there, I just don't know immediately which one -- suggestion (1) would help with this). 
3. I think having grid lines when there are a few disparate data points is a helpful guide for the eye (and then I'd put grid lines on all of them for consistency). 

If you want to address any of these suggestions that can be done in separate issues/pull requests. Otherwise it looks good!

**Comment by samgdotson** [comment]
Merging

**Comment by samgdotson** [comment]
I closed and commented the first time *facepalm*

**Pull request merged**
