### PR TITLE
Abstract

### LINKED ISSUE #1: Create abstract for ANS Student Conference 2020
This issue can be closed when a first draft of the abstract is added to the repo.

### PR DESCRIPTION
**Pull request by robfairh**
Fixes #1 

This PR contains the folder 'ans-abstract' with files necessary to build the following pdf of the abstract:
[abstract.pdf](https://github.com/arfc/2020-fairhurst-hydrogen-production/files/4067667/abstract.pdf)
(Go to the most recent comment for the latest version of the .pdf)

Additionally, the PR contains the file 'mtd-fuel-consumption.txt' with the data of the fuel consumed by MTD from July 1st, 2018 until June 30th, 2019.

### CODE REVIEW

**Comment by robfairh** [comment]
Latest version of the abstract in .pdf:
[abstract.pdf](https://github.com/arfc/2020-fairhurst-hydrogen-production/files/4071891/abstract.pdf)

**Comment by katyhuff** [comment]
Hi @robfairh and @samgdotson. Thanks for sharing. Please do another close edit internally before sending it back to me. I stopped at the first sentence which is missing a word and fails to expand an acronym (UIUC) on its first appearance. So, please review for grammar. There are many ways to review a document for grammar. I recommend using your text editor's capabilities for this (vim and emacs certainly have this capability), using a [python grammar checker](https://pypi.org/project/grammar-check/), using grammarly, or, perhaps @samgdotson should do a very close reading?

Since it seems you may have forgotten to apply the writing checklist. I have opened a new issue on this topic. #3 .

**Comment by robfairh** [comment]
Latest version of the document in .pdf:
[abstract.pdf](https://github.com/arfc/2020-fairhurst-hydrogen-production/files/4073801/abstract.pdf)

**Comment by robfairh** [comment]
Latest version of the document in .pdf:
[abstract.pdf](https://github.com/arfc/2020-fairhurst-hydrogen-production/files/4077973/abstract.pdf)

**Comment by katyhuff** [comment]
[abstract (1).pdf](https://github.com/arfc/2020-fairhurst-hydrogen-production/files/4079870/abstract.1.pdf)
   

Edits above....

**Comment by robfairh** [comment]
Latest (and submitted) version:
[abstract.pdf](https://github.com/arfc/2020-fairhurst-hydrogen-production/files/4080052/abstract.pdf)

**Review by samgdotson — APPROVED** [review]
I'd consider refining the writing a little more, but otherise it looks good to me.

**Pull request merged**
